disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple
  - identifier_name
  - trailing_comma
  - nesting
  - todo
  - superfluous_disable_command

opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - first_where
  - toggle_bool
  - empty_count
  - empty_string
  - fatal_error_message

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - DerivedData
  - dist
  - .release
